name: banksync
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.1.3
  freezed_annotation: ^2.2.0
  gap: ^3.0.0
  get_it: ^7.6.0
  injectable: ^1.5.3
  internet_connection_checker: ^1.0.0+1
  logger: ^1.3.0
  shared_preferences: ^2.1.1
 


dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  injectable_generator: ^1.5.3
  very_good_analysis: ^2.4.0


flutter:
  uses-material-design: true

  
  assets:
  
    - assets/icons/
    - assets/fonts/
    - assets/images/ 
    - .env.development
    - .env.production
    - .env.staging
 
  fonts:
    - family: Rambla
      fonts:
        - asset: assets/fonts/Rambla-Bold.ttf
        - asset: assets/fonts/Rambla-BoldItalic.ttf
        - asset: assets/fonts/Rambla-BoldItalic.ttf
        - asset: assets/fonts/Rambla-Italic.ttf
        - asset: assets/fonts/Rambla-Regular.ttf

       

   


